### ISSUE TITLE
How to use spades and set minimum coverage

### ISSUE THREAD

**Issue by Stupid747** [sanger-pathogens/ariba#215] opened 2018-03-14 11:57 UTC
Thanks for a great program. I’m new at linux and ariba so this might be stupid question. I wonder what is the command for setting spades as the assembler when performing a run.

I thought it was “ariba run [--assembler spades] ref reads_1.fq reads_2.fq output_dir

but I get error argument.

I also wonder if its possible to set a minimum coverage? We experience carryover between some sample when doing multiplexing in Illumina and we get a hit on genes we know are wrong, with few reads (around 5-10) and ctg_cov around 1-2.

Thanks for the help

**Comment by martinghunt** [comment] 2018-03-14 16:05
Re spades: that command looks correct. What error do you get? But in any case, unless you have a compelling reason for using spades, I recommend using the default assembler instead.

Re min coverage: you can filter the output file on the `ctg_cov` column, which is the mean read depth across the contig.

**Comment by Stupid747** [comment] 2018-03-14 17:26
when running the command I get

"ariba: error: unrecognized arguments: reads_2.fq output_dir

**Comment by martinghunt** [comment] 2018-03-15 10:53
What was the exact command that you ran?

**Comment by kpepper** [comment] 2019-04-03 11:00
This issue would have been caused by a mismatch/error in the program arguments provided. Closing due to age.

**Closed by kpepper** 2019-04-03 11:00 UTC
