### ISSUE TITLE
Installation failed: clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by abrozzi** [sanger-pathogens/ariba#245] opened 2018-11-27 15:06 UTC
While trying to install from pip3, got:

clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ithird_party/fermi-lite-0.1 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ariba/ext/fml-asm_ariba.cpp -o build/temp.macosx-10.10-x86_64-3.6/ariba/ext/fml-asm_ariba.o
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/bfc.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/bseq.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/bubble.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/htab.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/ksw.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/kthread.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/mag.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/misc.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/mrope.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/rld0.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/rle.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/rope.o build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/unitig.o build/temp.macosx-10.10-x86_64-3.6/ariba/ext/fml-asm_ariba.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.10-x86_64-3.6/fermilite_ariba.cpython-36m-darwin.so -lz
duplicate symbol _rle_auxtab in:
    build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/misc.o
    build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/rle.o
duplicate symbol _rle_auxtab in:
    build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/misc.o
    build/temp.macosx-10.10-x86_64-3.6/third_party/fermi-lite-0.1/rope.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1

**Comment by pgcudahy** [comment] 2019-02-16 08:38
Same issue for me too

**Comment by kpepper** [comment] 2019-03-18 16:34
What do you get when you execute: clang++ -v
?

**Comment by abrozzi** [comment] 2019-03-18 17:16
(py3.6) Users-MacBook-Air:~ ab$  clang++ -v

Apple LLVM version 10.0.0 (clang-1000.11.45.2)

Target: x86_64-apple-darwin17.7.0

Thread model: posix

InstalledDir:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by kpepper** [comment] 2019-03-18 17:21
Thanks.

I'm using clang-900.0.39.2 and not seeing this error, so may be clang-1000.11.45.2 is a little more strict. I think the [fermilite] third_party/fermi-lite-0.1/rule.h declaration _const uint8_t rle_auxtab[8];_ should actually have an extern in front - this may be the cause of the issue. If so, it's a line change.

**Comment by kpepper** [comment] 2019-03-21 16:15
I can replicate the issue and the code change fixes it. It's currently pushed to master and will be in the next release shortly.

**Closed by kpepper** 2019-03-21 16:15 UTC
