### ISSUE TITLE
getref error with resfinder db

### ISSUE THREAD

**Issue by hkaspersen** [sanger-pathogens/ariba#225] opened 2018-05-14 09:49 UTC
We are trying to run ARIBA with the resfinder database. However, when we tried to download the database, we got the following error:

The following command failed with exit code 128                                
git clone https://bitbucket.org/genomicepidemiology/resfinder_db.git /work/projects/nn9305k/ecoli/analysis/hkaspersen_map_pilot/ARIBA/resfinder_run/resfinderdb.tmp.download

The output was:

Initialized empty Git repository in /work/projects/nn9305k/ecoli/analysis/hkaspersen_map_pilot/ARIBA/resfinder_run/resfinderdb.tmp.download/.git/
git-remote-https: symbol lookup error: /usr/lib64/libnsssysinit.so: undefined symbol: PR_GetEnvSecure

FYI: I tried to clone the git repository separately, and it worked fine.

**Comment by martinghunt** [comment] 2018-05-14 10:42
I can't reproduce that. Could you please confirm if this throws an error?

`python3 -c 'import subprocess; subprocess.check_output("git clone https://bitbucket.org/genomicepidemiology/resfinder_db.git test.out", shell=True)'`

In any case, I have attached the output files so you can run `prepareref`
[getref.resfinder.fa.gz](https://github.com/sanger-pathogens/ariba/files/2000322/getref.resfinder.fa.gz)
[getref.resfinder.tsv.gz](https://github.com/sanger-pathogens/ariba/files/2000323/getref.resfinder.tsv.gz)

**Comment by hkaspersen** [comment] 2018-05-14 12:36
I ran your command also without errors. 

**Output from** `ariba version`:

WARNING: spades not found in path. Looked for spades.py
ARIBA version: 2.12.0

External dependencies:
bowtie2 2.2.9   /cluster/software/VERSIONS/bowtie2/2.2.9/bowtie2
cdhit   4.6     /cluster/software/VERSIONS/cd-hit/4.6.1/cd-hit-est
nucmer  3.1     /cluster/software/VERSIONS/mummer-3.23-64/bin/nucmer
spades  NA      NOT_FOUND

External dependencies OK: True

Python version:
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0]

Python packages:
ariba   2.12.0  /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/ariba/__init__.py
bs4     4.6.0   /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/bs4/__init__.py
dendropy        4.4.0   /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/dendropy/__init__.py
pyfastaq        3.17.0  /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/pyfastaq/__init__.py
pymummer        0.10.3  /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/pymummer/__init__.py
pysam   0.14.1  /work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True


**Operating system:**
`uname -a`
Linux login-0-1.local 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux


`lsb_release -a`
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final

**Comment by martinghunt** [comment] 2018-05-14 12:42
Thanks again. I guess for now you can use the attached files?

In the meantime I will use the same OS as you to try to reproduce the bug.

**Comment by kpepper** [comment] 2019-03-18 14:58
I’m closing this issue now as it’s old and doesn’t look like an Ariba problem. The error is emanating from the NSS (Network Security Services) package on CentOS.
That kind of link error could arise as a result of an out of date or corrupted package. I also haven’t been able to replicate this error on Linux or Mac. 
You could check with your sys admin to make sure you have recent NSS lib versions, and also try Ariba with recent versions of Python 3 and git.

**Closed by kpepper** 2019-03-18 14:58 UTC
